# Generated by Django 3.0.7 on 2020-08-08 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500, null=True)),
                ('phone_number', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=200, null=True)),
                ('last_Name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('birth_date', models.DateField(blank=True)),
                ('age', models.DecimalField(decimal_places=0, max_digits=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('NA', 'I do not wish to say')], max_length=2)),
                ('height', models.CharField(default='0.00 ft', max_length=10)),
                ('weight', models.CharField(default='0.00 lbs', max_length=10)),
                ('allergies', models.CharField(max_length=200, null=True)),
                ('emergency_contact_name', models.CharField(max_length=200, null=True)),
                ('emergency_contact_phone', models.CharField(max_length=200, null=True)),
                ('emergency_contact_address', models.CharField(max_length=200, null=True)),
                ('insurance_provider', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CovidScreening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.DecimalField(decimal_places=0, max_digits=50, null=True)),
                ('fever_above_100_F', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, null=True)),
                ('cough', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, null=True)),
                ('shortness_of_breath_or_difficulty_breathing', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, null=True)),
                ('sustained_loss_of_smell_or_taste', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, null=True)),
                ('body_aches', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, null=True)),
                ('vomiting_or_diarrhoea', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, null=True)),
                ('have_you_been_in_contact_with_COVID19_patient', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('NA', 'I do not know')], max_length=2, null=True)),
                ('have_you_been_to_any_COVID_affected_regions', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('NA', 'I do not know')], max_length=2, null=True)),
                ('patient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthcare.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='AssignTreatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare.Patient')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare.Treatment')),
            ],
            options={
                'ordering': ['treatment'],
            },
        ),
        migrations.CreateModel(
            name='AssignMed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare.Medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare.Patient')),
            ],
            options={
                'ordering': ['medication'],
            },
        ),
    ]
