# Generated by Django 3.0.7 on 2020-08-09 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_Date', models.DateField(blank=True)),
                ('pick_Time_Slot', models.CharField(blank=True, choices=[('8-9', '8am-9am'), ('9-10', '9am-10am'), ('10-11', '10am-11am'), ('11-12', '11am-12pm'), ('12-1', '12pm-1pm'), ('1-2', '1pm-2pm'), ('2-3', '2pm-3pm'), ('3-4', '3pm-4pm'), ('4-5', '4pm-5pm'), ('5-6', '5pm-6pm'), ('6-7', '6pm-7pm'), ('7-8', '7pm-8pm'), ('8-9', '8pm-9pm')], max_length=5)),
                ('Description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Approved'), ('D', 'Denied'), ('P', 'Pending')], default='P', max_length=2)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthcare.Patient')),
                ('staff', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
