# Generated by Django 3.0.7 on 2020-08-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_remove_patient_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
