# Generated by Django 3.0.7 on 2020-08-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_auto_20200809_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='staff',
        ),
        migrations.AddField(
            model_name='appointment',
            name='staff',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
