# Generated by Django 3.0.7 on 2020-08-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_patient_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='username',
        ),
    ]
