# Generated by Django 3.0.7 on 2020-08-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0004_remove_patient_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.DecimalField(decimal_places=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergyInfo',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.CharField(default='0.00 ft', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.CharField(default='0.00 lbs', max_length=10),
        ),
    ]
