# Generated by Django 3.0.7 on 2020-08-03 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0006_auto_20200802_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='firstName',
            new_name='first_Name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='lastName',
            new_name='last_Name',
        ),
    ]
