# Generated by Django 3.0.8 on 2020-08-09 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0006_contacttracing_periodicreporting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactTracing',
        ),
    ]
