# Generated by Django 3.0.7 on 2020-08-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0007_auto_20200809_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttracing',
            name='contact_information_of_person_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacttracing',
            name='contact_information_of_person_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacttracing',
            name='contact_information_of_person_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacttracing',
            name='contact_information_of_person_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacttracing',
            name='contact_information_of_person_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacttracing',
            name='contact_information_of_person_6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacttracing',
            name='full_name_of_person_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacttracing',
            name='full_name_of_person_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacttracing',
            name='full_name_of_person_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacttracing',
            name='full_name_of_person_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacttracing',
            name='full_name_of_person_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacttracing',
            name='full_name_of_person_6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacttracing',
            name='public_places_visited_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacttracing',
            name='public_places_visited_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacttracing',
            name='public_places_visited_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacttracing',
            name='public_places_visited_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
