# Generated by Django 3.0.7 on 2020-08-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0009_auto_20200809_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicreporting',
            name='flag',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
    ]
