# Generated by Django 3.0.7 on 2020-08-04 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0010_auto_20200803_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidScreening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.DecimalField(decimal_places=0, max_digits=50, null=True)),
                ('fever_above_100', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=2)),
                ('cough', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=2)),
                ('shortness_of_breath_or_difficulty_breathing', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=2)),
                ('sustained_loss_of_smell_or_taste', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=2)),
                ('body_aches', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=2)),
                ('vomiting_or_diarrhoea', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=2)),
                ('have_you_been_in_contact_with_COVID19_patient_or_one_who_had_close_contact_with_Covid19_patient', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=2)),
                ('have_you_been_to_any_COVID_affected_regions', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=2)),
                ('patient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthcare.Patient')),
            ],
        ),
    ]
