# Generated by Django 3.0.7 on 2020-08-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0011_auto_20200809_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Denied', 'Denied'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='covidscreening',
            name='body_aches',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='covidscreening',
            name='cough',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='covidscreening',
            name='fever_above_100_F',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='covidscreening',
            name='have_you_been_in_contact_with_COVID19_patient',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('NA', 'I do not know')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='covidscreening',
            name='have_you_been_to_any_COVID_affected_regions',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('NA', 'I do not know')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='covidscreening',
            name='shortness_of_breath_or_difficulty_breathing',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='covidscreening',
            name='sustained_loss_of_smell_or_taste',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='covidscreening',
            name='vomiting_or_diarrhoea',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('NA', 'I do not wish to say')], max_length=25),
        ),
        migrations.AlterField(
            model_name='patient',
            name='have_you_been_tested_positive_for_COVID',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='periodicreporting',
            name='body_aches',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='periodicreporting',
            name='cough',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='periodicreporting',
            name='fever_above_100_F',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='periodicreporting',
            name='flag',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='periodicreporting',
            name='shortness_of_breath_or_difficulty_breathing',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='periodicreporting',
            name='sustained_loss_of_smell_or_taste',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='periodicreporting',
            name='vomiting_or_diarrhoea',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
    ]
