# Generated by Django 3.0.7 on 2020-08-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0011_covidscreening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidscreening',
            name='body_aches',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='covidscreening',
            name='cough',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='covidscreening',
            name='fever_above_100',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='covidscreening',
            name='have_you_been_in_contact_with_COVID19_patient_or_one_who_had_close_contact_with_Covid19_patient',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('NA', 'I do not know')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='covidscreening',
            name='have_you_been_to_any_COVID_affected_regions',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('NA', 'I do not know')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='covidscreening',
            name='shortness_of_breath_or_difficulty_breathing',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='covidscreening',
            name='sustained_loss_of_smell_or_taste',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='covidscreening',
            name='vomiting_or_diarrhoea',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, null=True),
        ),
    ]
