# Generated by Django 3.0.8 on 2020-08-10 23:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('healthcare', '0012_auto_20200810_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='staff',
        ),
        migrations.AddField(
            model_name='appointment',
            name='staff',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
