# Generated by Django 3.0.7 on 2020-08-04 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0012_auto_20200803_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covidscreening',
            old_name='fever_above_100',
            new_name='fever_above_100_F',
        ),
    ]
