# Generated by Django 3.0.7 on 2020-08-10 23:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0012_auto_20200809_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttracing',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
