# Generated by Django 3.0.7 on 2020-08-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0013_contacttracing_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='staff',
            field=models.CharField(choices=[('Dr. Ross Green', 'Dr. Ross Green'), ('Dr. Janice Bing', 'Dr. Janice Bing'), ('Dr. Joey Tribbiani', 'Dr. Joey Tribbiani'), ('Dr. Drake Ramorayn', 'Dr. Drake Ramorayn'), ('Dr. Emilie Geller', 'Dr. Emilie Geller')], max_length=200, null=True),
        ),
    ]
