# Generated by Django 3.0.7 on 2020-08-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0015_auto_20200804_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
