# Generated by Django 3.0.7 on 2020-08-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0016_patient_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
