# Generated by Django 3.0.8 on 2020-08-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0018_assignmed_assigntreatment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmed',
            options={'ordering': ['medication']},
        ),
        migrations.AlterModelOptions(
            name='assigntreatment',
            options={'ordering': ['treatment']},
        ),
    ]
