# Generated by Django 3.0.7 on 2020-08-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0019_auto_20200806_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
