# Generated by Django 3.0.7 on 2020-08-08 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0020_auto_20200807_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covidscreening',
            old_name='have_you_been_in_contact_with_COVID19_patient_or_one_who_had_close_contact_with_Covid19_patient',
            new_name='have_you_been_in_contact_with_COVID19_patient',
        ),
    ]
