# Generated by Django 3.0.7 on 2020-08-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0021_auto_20200807_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testlocation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='testlocation',
            name='website',
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True),
        ),
    ]
